# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(max_length=255)),
                ('urlques', models.CharField(max_length=1000)),
                ('urlans', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=1000)),
            ],
        ),
    ]
